version: "3"

services:
  
  api01:
    container_name: api01
    build: ./api

    environment:
      - MESSAGE=${NOMBRE}
    ports:
      - "3000:3000"

  
  api02:
    container_name: api02
    build: ./api

    environment:
      - MESSAGE=${NOMBRE2}
    ports:
      - "3001:3000"
    
